export const productsLaptops = [
    {
        name: 'Lenovo',
        model: 'Legion 5 Gaming Laptop',
        year:  2020,
        price: 990.78,
        url: 'https://content2.onliner.by/catalog/device/header/8eb1c67235cf82845223a7c51a3c1ba8.jpeg',
        country: 'China',
        casingMaterial: 'Plastic',
        processorBaseFrequency: 2500,
        processorCores: 4,
        processorModel: 'Intel Core i5 10300H',
        screenResolution: '1920x1080',
        screenSize: 15.6,
        storageType: 'SSD',
        systemMemory: 16,
        totalStorageCapacity: 512,
        graphicsAdapter: 'NVIDIA GeForce GTX 1650 Ti 4 GB',
        platform: 'Windows 10',
        article: '82AU00BDRE',
    },
    {
        name: 'MSI',
        model: 'GE75 Raider',
        year:  2020,
        price: 2500,
        url: 'https://content2.onliner.by/catalog/device/header/701ecca43c0633487bfefe2720229df3.jpeg',
        country: 'Taiwan',
        casingMaterial: 'Plastic',
        processorBaseFrequency: 2500,
        processorCores: 8,
        processorModel: 'Intel Core i7 10875H',
        screenResolution: '1920x1080',
        screenSize: 17.3,
        storageType: 'SSD',
        systemMemory: 16,
        totalStorageCapacity: '1000+512',
        graphicsAdapter: 'NVIDIA GeForce GTX RTX 2070 8GB',
        platform: 'Windows 10',
        article: 'X512DABQ1134',
    },
    {
        name: 'HONOR',
        model: 'MagicBook 14',
        year:  2020,
        price: 805.48 ,
        url: 'https://content2.onliner.by/catalog/device/header/53e03cc53a4b03efaa62bb07547528ec.jpeg',
        country: 'China',
        casingMaterial: 'Metal',
        processorBaseFrequency: 2100,
        processorCores: 4,
        processorModel: 'AMD Ryzen 5 3500U',
        screenResolution: '1920x1080',
        screenSize: 14,
        storageType: 'SSD',
        systemMemory: 8,
        totalStorageCapacity: 512,
        graphicsAdapter: 'Integrated',
        platform: 'Windows 10',
        article: '53010VTY',
    },
    {
        name: 'ASUS',
        model: 'VivoBook 15',
        year:  2019,
        price: 633,
        url: 'https://content2.onliner.by/catalog/device/header/21d9a30aa2f58b37a31d0a961fa87437.jpeg',
        country: 'Taiwan',
        casingMaterial: 'Plastic',
        processorBaseFrequency: 2100,
        processorCores: 4,
        processorModel: 'AMD Ryzen 5 3500U',
        screenResolution: '1920x1080',
        screenSize: 15.6,
        storageType: 'SSD',
        systemMemory: 8,
        totalStorageCapacity: 512,
        graphicsAdapter: 'Embedded',
        platform: 'Linux',
        article: '53010VTY',
    }
];

export const productsPhones = [
    {
        id: '0',
        name: 'Apple iPhone',
        model: '12 Pro',
        year:  2020,
        price: 1190,
        url: 'https://content2.onliner.by/catalog/device/header/a5e2764b76188d4ffe32fefeb0a6b9be.jpeg',
        country: 'USA',
        casingMaterial: 'Metal',
        processorBaseFrequency: 2990,
        processorCores: 6,
        processorModel: 'Apple A14 Bionic',
        screenResolution: '1170x2532',
        screenSize: 6.1,
        systemMemory: 6,
        totalStorageCapacity: 128,
        type: 'Smartphone',
        platform: 'iOS',
        color: '(Graphite)',
        camera: '12 MP *3',
        battery: '2815mAh',
    },
    {
        id: '1',
        name: 'Samsung',
        model: 'Galaxy S21 Ultra 5G',
        year:  2021,
        price: 1700,
        url: 'https://content2.onliner.by/catalog/device/header/f24c742ad873ecc77a5b531e5e596e09.jpeg',
        country: 'South Korea',
        casingMaterial: 'Metal',
        processorBaseFrequency: 2900,
        processorCores: 8,
        processorModel: 'Exynos 2100',
        screenResolution: '1440x3200',
        screenSize:  6.8,
        systemMemory: 12,
        totalStorageCapacity: 128,
        type: 'Smartphone',
        platform: 'Android',
        color: '(Black Phantom)',
        camera: '108 MP',
        battery: '5000 mAh',
    },
    {
        id: '2',
        name: 'Huawei',
        model: 'P smart',
        year:  2020,
        price: 265 ,
        url: 'https://content2.onliner.by/catalog/device/header/8d9186c7db3e7235287a7b665eb3640f.jpeg',
        country: 'China',
        casingMaterial: 'Plastic',
        processorBaseFrequency: 2000,
        processorCores: 8,
        processorModel: 'HiSilicon Kirin 710A',
        screenResolution: '1080x2400',
        screenSize: 6.67,
        systemMemory: 4,
        totalStorageCapacity: 128,
        type: 'Smartphone',
        platform: 'Android',
        color: '(Bright Green)',
        camera: '48 MP',
        battery: '5000 mAh',
    },
    {
        id: '3',
        name: 'HONOR',
        model: '10X Lite DNN-LX9',
        year:  2020,
        price: 203 ,
        url: 'https://content2.onliner.by/catalog/device/header/42d35bd50bd153fe4027758fc72679af.jpeg',
        country: 'China',
        casingMaterial: 'Plastic',
        processorBaseFrequency: 2000,
        processorCores: 8,
        processorModel: 'HiSilicon Kirin 710A',
        screenResolution: '1080x2400',
        screenSize: 6.67,
        systemMemory: 4,
        totalStorageCapacity: 128,
        type: 'Smartphone',
        platform: 'Android',
        color: '(Emerald Green)',
        camera: '48 MP',
        battery: '5000 mAh',
    },
];

export const productsSmartWatch = [
    {
        id: '0',
        name: 'Apple Watch',
        model: 'SE',
        year:  2020,
        price: 366.13,
        url: 'https://content2.onliner.by/catalog/device/header/de676744b4d6fd5a46c1d9437c866f46.jpeg',
        country: 'USA',
        casingMaterial: 'Aluminum',
        screenResolution: '368x448',
        screenSize: 1.78,
        systemMemory: '',
        totalStorageCapacity: 32,
        type: 'Smart watch',
        platform: 'iOS support',
        color: '(Space Gray / Sports Black)',
        battery: 'Li-ion',
        workingHours: '18 hours',
    },
    {
        id: '1',
        name: 'Samsung',
        model: 'Galaxy Watch3',
        year:  2020,
        price: 343.01,
        url: 'https://content2.onliner.by/catalog/device/header/82deec09d01c700e08317a9a82d692db.jpeg',
        country: 'South Korea',
        casingMaterial: 'Metal',
        screenResolution: '360x360',
        screenSize:  1.4,
        systemMemory: 1,
        totalStorageCapacity: 8,
        type: 'Smart watch',
        platform: 'support for Android / iOS',
        color: '(Black)',
        battery: 'Li-ion',
        workingHours: '3 days',
    },
    {
        id: '2',
        name: 'HONOR',
        model: 'MagicWatch 2',
        year:  2019,
        price: 105.16,
        url: 'https://content2.onliner.by/catalog/device/header/3220bd5c96e6981212f77c08fbd74b7b.jpeg',
        country: 'South Korea',
        casingMaterial: 'Metal',
        screenResolution: '390x390',
        screenSize:  1.2,
        systemMemory: 0.32,
        totalStorageCapacity: 4,
        type: 'Smart watch',
        platform: 'support for Android / iOS',
        color: '(Rose Gold)',
        battery: 'Li-ion',
        workingHours: '1 week',
    },
    {
        id: '3',
        name: 'Huawei',
        model: 'Watch GT2 Pro',
        year:  2020,
        price: 177.73,
        url: 'https://content2.onliner.by/catalog/device/header/001af6592c1f6a4b680423ecf079152b.jpeg',
        country: 'South Korea',
        casingMaterial: 'Metal',
      
        screenResolution: '454x454',
        screenSize:  1.39,
        systemMemory: 0.32,
        totalStorageCapacity: 4,
        type: 'Smart watch',
        platform: 'support for Android / iOS',
        color: '(Hazy Gray)',
        battery: 'Li-ion',
        workingHours: '2 week',
    },
];

export const productsDisplay  = [
    {
        name: 'Prestigio',
        price: 788.96,
        url: 'https://content2.onliner.by/catalog/device/header/b2d1272d268b4309059153fe7e080431.jpeg',
        country: 'Cyprus',
        casingMaterial: 'Plastic',
        screenResolution: '	3840x2160',
        screenSize: 42.5,
        brightness: '350 кд/м2',
        article: 'PDSIK43WNN0L',
    },
    {
        name: 'Dell',
        price: 10580.05,
        url: 'https://content2.onliner.by/catalog/device/header/4d37c37435cecda56b982de77b0e3f1f.jpeg',
        country: 'USA',
        casingMaterial: 'Plastic',
        screenResolution: '	3840x2160',
        screenSize: 86,
        brightness: '400 кд/м2',
        article: 'C8618QT',
    },
    {
        name: 'Samsung',
        price: 1602.53,
        url: 'https://content2.onliner.by/catalog/device/header/cf25b76df886da88cf56c91fa34c83f0.jpeg',
        country: 'South Korea',
        casingMaterial: 'Plastic',
        screenResolution: '	1920x1080',
        screenSize: 43,
        brightness: '500 кд/м2',
        article: 'LH43PMFPBGC',
    },
];

export const productsTV  = [
    {
        name: 'Samsung',
        model: 'Smart TV',
        year:  2020,
        price: 612.75,
        url: 'https://content2.onliner.by/catalog/device/header/013fa8c0ecd829268d590b92d67326bd.jpeg',
        country: 'South Korea',
        casingMaterial: 'Plastic',
        screenResolution: '	3840x2160 (4K UHD)',
        screenSize: 50,
        platform: 'Samsung Tizen',
        article: 'UE50TU8570U',
    },
    {
        name: 'Samsung',
        model: 'TV',
        year:  2020,
        price: 303.47,
        url: 'https://content2.onliner.by/catalog/device/header/a5d446091a92f25109f8d34d2b41104f.jpeg',
        country: 'South Korea',
        casingMaterial: 'Plastic',
        screenResolution: '	1920x1080 (Full HD)',
        screenSize: 32,
        platform: 'Samsung Tizen',
        article: 'UE32T5300AU',
    },
    {
        name: 'Xiaomi',
        model: 'MI TV P1',
        year:  2021,
        price: 219.25,
        url: 'https://content2.onliner.by/catalog/device/header/9d23d62ea0c9e9335d44037203d347a5.jpeg',
        country: 'China',
        casingMaterial: 'Plastic',
        screenResolution: '	1366x768 (HD)',
        screenSize: 32,
        platform: 'Android TV',
        article: 'UE99T52500U',
    },
];