export const productsLaptops = [
    {
        name: 'Lenovo',
        model: 'Legion 5 Gaming Laptop',
        year:  2020,
        price: 990.78,
        url: 'https://content2.onliner.by/catalog/device/header/8eb1c67235cf82845223a7c51a3c1ba8.jpeg',
        country: 'China',
        casingMaterial: 'Plastic',
        processorBaseFrequency: 2500,
        processorCores: 4,
        processorModel: 'Intel Core i5 10300H',
        screenResolution: '1920x1080',
        screenSize: 15.6,
        storageType: 'SSD',
        systemMemory: 16,
        totalStorageCapacity: 512,
        graphicsAdapter: 'NVIDIA GeForce GTX 1650 Ti 4 GB',
        platform: 'Windows 10',
        article: '82AU00BDRE',
    },
    {
        name: 'MSI',
        model: 'GE75 Raider',
        year:  2020,
        price: 2500,
        url: 'https://content2.onliner.by/catalog/device/header/701ecca43c0633487bfefe2720229df3.jpeg',
        country: 'Taiwan',
        casingMaterial: 'Plastic',
        processorBaseFrequency: 2500,
        processorCores: 8,
        processorModel: 'Intel Core i7 10875H',
        screenResolution: '1920x1080',
        screenSize: 17.3,
        storageType: 'SSD',
        systemMemory: 16,
        totalStorageCapacity: '1000+512',
        graphicsAdapter: 'NVIDIA GeForce GTX RTX 2070 8GB',
        platform: 'Windows 10',
        article: 'X512DABQ1134',
    },
    {
        name: 'HONOR',
        model: 'MagicBook 14',
        year:  2020,
        price: 805.48 ,
        url: 'https://content2.onliner.by/catalog/device/header/53e03cc53a4b03efaa62bb07547528ec.jpeg',
        country: 'China',
        casingMaterial: 'Metal',
        processorBaseFrequency: 2100,
        processorCores: 4,
        processorModel: 'AMD Ryzen 5 3500U',
        screenResolution: '1920x1080',
        screenSize: 14,
        storageType: 'SSD',
        systemMemory: 8,
        totalStorageCapacity: 512,
        graphicsAdapter: 'Integrated',
        platform: 'Windows 10',
        article: '53010VTY',
    },
    {
        name: 'ASUS',
        model: 'VivoBook 15',
        year:  2019,
        price: 633,
        url: 'https://content2.onliner.by/catalog/device/header/21d9a30aa2f58b37a31d0a961fa87437.jpeg',
        country: 'Taiwan',
        casingMaterial: 'Plastic',
        processorBaseFrequency: 2100,
        processorCores: 4,
        processorModel: 'AMD Ryzen 5 3500U',
        screenResolution: '1920x1080',
        screenSize: 15.6,
        storageType: 'SSD',
        systemMemory: 8,
        totalStorageCapacity: 512,
        graphicsAdapter: 'Embedded',
        platform: 'Linux',
        article: '53010VTY',
    }
];

export const productsPhones = [
    {
        name: 'Apple iPhone',
        model: '12 Pro',
        year:  2020,
        price: 1190,
        url: 'https://content2.onliner.by/catalog/device/header/a5e2764b76188d4ffe32fefeb0a6b9be.jpeg',
        country: 'USA',
        casingMaterial: 'Metal',
        processorBaseFrequency: 2990,
        processorCores: 6,
        processorModel: 'Apple A14 Bionic',
        screenResolution: '1170x2532',
        screenSize: 6.1,
        systemMemory: 6,
        totalStorageCapacity: 128,
        type: 'Smartphone',
        platform: 'iOS',
        color: '(Graphite)',
        camera: '12 MP *3',
        battery: '2815mAh',
    },
    {
        name: 'Samsung',
        model: 'Galaxy S21 Ultra 5G',
        year:  2021,
        price: 1700,
        url: 'https://content2.onliner.by/catalog/device/header/f24c742ad873ecc77a5b531e5e596e09.jpeg',
        country: 'South Korea',
        casingMaterial: 'Metal',
        processorBaseFrequency: 2900,
        processorCores: 8,
        processorModel: 'Exynos 2100',
        screenResolution: '1440x3200',
        screenSize:  6.8,
        systemMemory: 12,
        totalStorageCapacity: 128,
        type: 'Smartphone',
        platform: 'Android',
        color: '(Black Phantom)',
        camera: '108 MP',
        battery: '5000 mAh',
    },
    {
        name: 'Huawei',
        model: 'P smart',
        year:  2020,
        price: 265 ,
        url: 'https://content2.onliner.by/catalog/device/header/8d9186c7db3e7235287a7b665eb3640f.jpeg',
        country: 'China',
        casingMaterial: 'Plastic',
        processorBaseFrequency: 2000,
        processorCores: 8,
        processorModel: 'HiSilicon Kirin 710A',
        screenResolution: '1080x2400',
        screenSize: 6.67,
        systemMemory: 4,
        totalStorageCapacity: 128,
        type: 'Smartphone',
        platform: 'Android',
        color: '(Bright Green)',
        camera: '48 MP',
        battery: '5000 mAh',
    },
    {
        name: 'HONOR',
        model: '10X Lite DNN-LX9',
        year:  2020,
        price: 203 ,
        url: 'https://content2.onliner.by/catalog/device/header/42d35bd50bd153fe4027758fc72679af.jpeg',
        country: 'China',
        casingMaterial: 'Plastic',
        processorBaseFrequency: 2000,
        processorCores: 8,
        processorModel: 'HiSilicon Kirin 710A',
        screenResolution: '1080x2400',
        screenSize: 6.67,
        systemMemory: 4,
        totalStorageCapacity: 128,
        type: 'Smartphone',
        platform: 'Android',
        color: '(Emerald Green)',
        camera: '48 MP',
        battery: '5000 mAh',
    },
];
